In [172]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
from sklearn.decomposition import PCA

In [173]:
df=pd.read_csv("insurance.csv")
df

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [174]:
label_encoder = LabelEncoder()
df["smoker"]=label_encoder.fit_transform(df["smoker"])
df["region"]=label_encoder.fit_transform(df["region"])
df["sex"]=label_encoder.fit_transform(df["sex"])

In [175]:
df

age  sex     bmi  children  smoker  region      charges
0      19    0  27.900         0       1       3  16884.92400
1      18    1  33.770         1       0       2   1725.55230
2      28    1  33.000         3       0       2   4449.46200
3      33    1  22.705         0       0       1  21984.47061
4      32    1  28.880         0       0       1   3866.85520
...   ...  ...     ...       ...     ...     ...          ...
1333   50    1  30.970         3       0       1  10600.54830
1334   18    0  31.920         0       0       0   2205.98080
1335   18    0  36.850         0       0       2   1629.83350
1336   21    0  25.800         0       0       3   2007.94500
1337   61    0  29.070         0       1       1  29141.36030

[1338 rows x 7 columns]

In [176]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   int32  
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   int32  
 5   region    1338 non-null   int32  
 6   charges   1338 non-null   float64
dtypes: float64(2), int32(3), int64(2)
memory usage: 57.6 KB


In [177]:
#arger values of epsilon allow for more errors to be ignored within the margin, potentially leading to a more robust model against noise but with reduced precisio

In [178]:
x=df.drop(columns=["charges"])
y=df["charges"]
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)
y_scaled = scaler.fit_transform(y.values.reshape(-1, 1))
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y_scaled,test_size=0.2,random_state=343)
model=SVR(kernel="rbf",degree=3,C=2.0,epsilon=0.1)
model.fit(x_train,y_train)
y_pred_test=model.predict(x_test)
y_pred_train=model.predict(x_train)
test_accuracy=r2_score(y_pred_test,y_test)
train_accuracy=r2_score(y_train,y_pred_train)
print("this is test accurcay",test_accuracy)
print("this is train accurcay",train_accuracy)

this is test accurcay 0.8081074233344847
this is train accurcay 0.8639912636271802


E:\anacondafolder\Lib\site-packages\sklearn\utils\validation.py:1229: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### Applying principal component analysis

In [239]:
pca=PCA(n_components=5)
#if n_components not specified all features it will take or svd_solver="full"

In [240]:
principal_components = pca.fit_transform(x_scaled)
principal_components


array([[ 0.4138055 ,  1.11914688, -1.78482549,  0.68409261,  2.1492386 ],
       [-0.12275981,  0.8221422 , -1.00416857,  0.83286115, -1.13903812],
       [-0.62442365,  0.6374776 ,  0.55788538,  1.54161695, -1.05905363],
       ...,
       [-0.01196397, -0.53097399, -1.89164153,  0.52494884,  0.19458612],
       [ 0.65020071, -0.58750209, -1.93950587,  1.06112088,  0.40162833],
       [ 0.10392973,  0.09896763,  0.44724209, -1.7904566 ,  2.18741871]])

In [241]:
explained_variance = pca.explained_variance_
explained_variance

array([1.20451879, 1.08901232, 1.02030138, 0.9659841 , 0.92465654])

In [242]:
a_train,a_test,b_train,b_test=train_test_split(principal_components,y_scaled,test_size=0.2,random_state=343)

In [243]:
a_train.shape

(1070, 5)

In [244]:
model=SVR(kernel="rbf",degree=3,C=2.0,epsilon=0.1)
model.fit(a_train,b_train)
y_pred_test=model.predict(a_test)
y_pred_train=model.predict(a_train)
test_accuracy=r2_score(y_pred_test,b_test)
train_accuracy=r2_score(b_train,y_pred_train)
print("this is test accurcay",test_accuracy)
print("this is train accurcay",train_accuracy)

this is test accurcay 0.743231382813101
this is train accurcay 0.8263521103007188


E:\anacondafolder\Lib\site-packages\sklearn\utils\validation.py:1229: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [245]:
help(pca)

Help on PCA in module sklearn.decomposition._pca object:

class PCA(sklearn.decomposition._base._BasePCA)
 |  PCA(n_components=None, *, copy=True, whiten=False, svd_solver='auto', tol=0.0, iterated_power='auto', n_oversamples=10, power_iteration_normalizer='auto', random_state=None)
 |  
 |  Principal component analysis (PCA).
 |  
 |  Linear dimensionality reduction using Singular Value Decomposition of the
 |  data to project it to a lower dimensional space. The input data is centered
 |  but not scaled for each feature before applying the SVD.
 |  
 |  It uses the LAPACK implementation of the full SVD or a randomized truncated
 |  SVD by the method of Halko et al. 2009, depending on the shape of the input
 |  data and the number of components to extract.
 |  
 |  It can also use the scipy.sparse.linalg ARPACK implementation of the
 |  truncated SVD.
 |  
 |  Notice that this class does not support sparse input. See
 |  :class:`TruncatedSVD` for an alternative with sparse data.
 |  


In [246]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import numpy as np

# Example data
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Standardize data (optional but recommended)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Apply PCA
pca = PCA(n_components=1)  # Reduce to 2 principal components
X_pca = pca.fit_transform(X_scaled)

# Explained variance ratio
print("Explained Variance Ratio:", pca.explained_variance_ratio_)
print("Principal Components:\n", pca.components_)


Explained Variance Ratio: [1.]
Principal Components:
 [[-0.57735027 -0.57735027 -0.57735027]]


In [247]:
pca.components_

array([[-0.57735027, -0.57735027, -0.57735027]])